### ISSUE TITLE
Terraform Provider not supporting few ES Templates

### ISSUE THREAD

**Issue by ggsood** [elastic/terraform-provider-ec#129]
The current version of terraform provider does not support creation of certain ES templates like CCS clusters.
The CCS clusters doesn't have an APM, Enterprise Search and App Search Resource.
The code currently checks them in the template API Response,  code checks need to be handled in this case.

## Readiness Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
The CCS cluster should get created as per the template.

## Current Behavior
Getting the following error when running the terraform resource

```hcl
resource "ec_deployment" "defaults" {
  name                   = "ccs-cluster"
  region                 = "us-east-1"
  version                = "7.9.2"
  deployment_template_id = "aws-cross-cluster-search-v2"

  elasticsearch {
    topology {
      size = "1g"
    }
  }

  kibana {
    topology {
      size = "1g"
    }
  }
}
```

## Possible Solution
Add nil checks for APM and Enterprise Resources in deployment template.

## Steps to Reproduce
Run the terraform code provided above with the latest version of code.

## Context
Unable to create CCS cluster

## Your Environment

* Version used: master
* Environment name and version (e.g. Go 1.9): 1.13
* Server type and version: Mac
* Operating System and version: MacOS

**Comment by marclop** [comment]
You forgot to include the returned error, only posted the `hcl` definition, I'd be keen to know what error was thrown.

**Comment by ggsood** [comment]
Apologies for that @marclop , please find the error stack below
```
panic: runtime error: index out of range [0] with length 0
2020-10-14T17:44:15.070+0100 [DEBUG] plugin.terraform-provider-ec_v1.0.1: 
2020-10-14T17:44:15.070+0100 [DEBUG] plugin.terraform-provider-ec_v1.0.1: goroutine 23 [running]:
2020-10-14T17:44:15.070+0100 [DEBUG] plugin.terraform-provider-ec_v1.0.1: github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.apmResource(...)
2020-10-14T17:44:15.070+0100 [DEBUG] plugin.terraform-provider-ec_v1.0.1:       github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/testutil_func.go:68
2020-10-14T17:44:15.070+0100 [DEBUG] plugin.terraform-provider-ec_v1.0.1: github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.createResourceToModel(0xc000360c80, 0xc0001f4860, 0x40, 0x1fcafe0, 0x25a84f0)
2020-10-14T17:44:15.070+0100 [DEBUG] plugin.terraform-provider-ec_v1.0.1:       github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/expanders.go:64 +0xdc3
2020-10-14T17:44:15.070+0100 [DEBUG] plugin.terraform-provider-ec_v1.0.1: github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.createResource(0x2603bc0, 0xc0005b35c0, 0xc000360c80, 0x1f78320, 0xc0001f4860, 0xc000813d80, 0x188e55a, 0xc000b31680)
```
