### ISSUE TITLE
Config blocks unable to handle default empty or omitted settings

### ISSUE THREAD

**Issue by Crazybus** [elastic/terraform-provider-ec#345]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

No changes are detected and the provider does not crash.
## Current Behavior

When declaring an elasticsearch.config block that has only `null` settings the provider crashes. A short snippet looks like:

```
elasticsearch {
  config {
    user_settings_yaml = null
  }
}
```

<details>
<summary>Crash logs</summary>

```
ec_deployment.example_minimal: Creating...
╷
│ Error: Request cancelled
│
│   with ec_deployment.example_minimal,
│   on main.tf line 21, in resource "ec_deployment" "example_minimal":
│   21: resource "ec_deployment" "example_minimal" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request
│ was cancelled.
╵

Stack trace from the terraform-provider-ec_v0.3.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 87 [running]:
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandEsConfig(0x132fa40, 0xc00069ac60, 0xc00080e480, 0x6, 0xc0002742c8)
        /home/mick/pro/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch_expanders.go:256 +0x5c5
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandEsResource(0x13f1ea0, 0xc000660870, 0xc000660660, 0xc00013ffa0, 0xc000543260, 0x40fe58)
        /home/mick/pro/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch_expanders.go:92 +0x9dd
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandEsResources(0xc000520ad0, 0x1, 0x1, 0xc000660660, 0x6, 0x21abd01, 0xc000660660, 0x0, 0xc000970000)
        /home/mick/pro/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch_expanders.go:51 +0xc5
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.createResourceToModel(0xc000617880, 0xc000128af8, 0x40, 0x13585e0, 0x180c3c0)
        /home/mick/pro/terraform-provider-ec/ec/ecresource/deploymentresource/expanders.go:66 +0x57c
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.createResource(0x1850c58, 0xc00070ff20, 0xc000617880, 0x1308320, 0xc000128af8, 0xc000785f10, 0xd6ed0a, 0xc000426b80)
        /home/mick/pro/terraform-provider-ec/ec/ecresource/deploymentresource/create.go:36 +0xc8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0004637a0, 0x1850be8, 0xc000150900, 0xc000617880, 0x1308320, 0xc000128af8, 0x0, 0x0, 0x0)
        /home/mick/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:330 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004637a0, 0x1850be8, 0xc000150900, 0xc000326770, 0xc000426b80, 0x1308320, 0xc000128af8, 0x0, 0x0, 0x0, ...)
        /home/mick/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00059e2a0, 0x1850be8, 0xc000150900, 0xc000153400, 0xc000150900, 0x15a9400, 0xc0003a2200)
        /home/mick/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00014cda0, 0x1850c90, 0xc000150900, 0xc000326540, 0xc00014cda0, 0xc0003a2210, 0xc000087ba0)
        /home/mick/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x15a9400, 0xc00014cda0, 0x1850c90, 0xc0003a2210, 0xc00070f1a0, 0x0, 0x1850c90, 0xc0003a2210, 0xc0002e8300, 0x67c)
        /home/mick/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005b5dc0, 0x185acf8, 0xc000583800, 0xc0001c0a00, 0xc00033b8c0, 0x2165860, 0x0, 0x0, 0x0)
        /home/mick/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0005b5dc0, 0x185acf8, 0xc000583800, 0xc0001c0a00, 0x0)
        /home/mick/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000048350, 0xc0005b5dc0, 0x185acf8, 0xc000583800, 0xc0001c0a00)
        /home/mick/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/mick/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-ec_v0.3.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
</details>

## Terraform definition

```
terraform {
  required_version = ">= 0.12.29"

  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "0.3.0"
    }
  }
}

provider "ec" {}

data "ec_stack" "latest" {
  version_regex = "latest"
  region        = "us-east-1"
}

resource "ec_deployment" "example_minimal" {
  name = "my_example_deployment"

  region                 = "gcp-us-central1"
  version                = data.ec_stack.latest.version
  deployment_template_id = "gcp-hot-warm"

  elasticsearch {
    config {
      user_settings_yaml = null
    }
  }
  kibana {}
}

```

## Steps to Reproduce
1. Create main.tf with the above snippet
2. `terraform apply`

## Context

This situation occurs when using the provider as part of a module. You want the default settings to be "default if it not set" and you want to allow the user to override the setting.

For the Elasticsearch user_settings this looks like:

```
variable "cluster_settings" {
  description = "Elasticsearch Cluster settings"
  default     = {}
  type        = map(any)
}

# Removed the rest of the definition for brevity
elasticsearch {
  config {
    user_settings_json = jsonencode(var.elasticsearch_config)
  }
}
```

However doing this results in detected changes every time with the default of `{}`. So instead I tried to set the default to `null` to omit the settings with something like:

```
user_settings_json = length(var.elasticsearch_config) == 0 ? null : jsonencode(var.elasticsearch_config)
```

As a workaround I am currently using the yaml settings and adding an empty comment to make sure the config exists but isn't empty:

```
user_settings_yaml = length(var.elasticsearch_config) == 0 ? "# empty" : yamlencode(var.elasticsearch_config)
```

Unfortunately a workaround like this won't work for all settings. As an example for plugins this would not be possible because setting `plugins = []` fails because it needs a minimum length of 1.

## Possible Solution

Couple of ideas I can think of:

1. Making sure that the blocks can handle situations where all settings are `null` and nothing is actually set
2. Providing a way to set a default "empty" value for all settings. E.g. Accepting `plugins = []` and `user_settings_yaml = ""`

## Your Environment
* Version used: Latest git commit: 50882b69b64969aee46f3e2ed80b4fd7a664ac21 
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud SaaS
* Environment name and version (e.g. Go 1.9): `go version go1.16.6 linux/amd64`
* Operating System and version: Arch Linux

**Comment by marclop** [comment]
Thanks for opening the issue @Crazybus, I'll fix the issue as soon as I can.
