### ISSUE TITLE
`terraform apply` from docker container against imported cluster causes SIGSEGV 

### ISSUE THREAD

**Issue by jaynefox** [elastic/terraform-provider-ec#407]
## Readiness Checklist

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

`terraform apply` should apply the changes reported by `terraform plan`

## Current Behavior

`terraform plan` succeeds with a couple of minor changes. `terraform apply` gets me:

```
│ Error: Plugin did not respond
│
│   with ec_deployment.monitoring,
│   on main.tf line 17, in resource "ec_deployment" "monitoring":
│   17: resource "ec_deployment" "monitoring" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-ec_v0.3.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x10751b9]

goroutine 76 [running]:
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandEsConfig({0x1136480, 0xc00058cf18}, 0x0)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch_expanders.go:285 +0x1d9
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandEsTopology({0x1136480, 0xc00058cf60}, {0xc00096ae10, 0x7, 0x9})
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch_expanders.go:251 +0x3a7
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandEsResource({0x11f5d60, 0xc00072efc0}, 0xc0006de810)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch_expanders.go:80 +0x279
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandEsResources({0xc0004506a0, 0x1, 0x11}, 0xc00046f958)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch_expanders.go:51 +0xbc
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.updateResourceToModel(0x0, 0xc00000c5b8)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/expanders.go:172 +0x8a5
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.updateDeployment({0xc00055d6a8, 0xc00055d740}, 0xc000851d00, 0xc00000c5b8)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/update.go:53 +0x45
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.updateResource({0x163d278, 0xc0006ef740}, 0xc00055d778, {0x11162c0, 0xc00000c5b8})
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/update.go:36 +0x7d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000243880, {0x163d208, 0xc000139640}, 0x24, {0x11162c0, 0xc00000c5b8})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:364 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000243880, {0x163d208, 0xc000139640}, 0xc00042b520, 0xc000331700, {0x11162c0, 0xc00000c5b8})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:464 +0x6ba
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00058c228, {0x163d208, 0xc000139640}, 0xc00096b090)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000435da0, {0x163d2b0, 0xc00028a930}, 0xe58758bdc0732eba)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x139bc00, 0xc000435da0}, {0x163d2b0, 0xc00028a930}, 0xc000666ae0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000320000, {0x164f718, 0xc000418000}, 0xc00054a240, 0xc000322180, 0x2041e40, 0x0)
	google.golang.org/grpc@v1.38.0/server.go:1286 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc000320000, {0x164f718, 0xc000418000}, 0xc00054a240, 0x0)
	google.golang.org/grpc@v1.38.0/server.go:1609 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.38.0/server.go:934 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.38.0/server.go:932 +0x294

Error: The terraform-provider-ec_v0.3.0 plugin crashed!
```

## Terraform definition

```
terraform {
  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "~> 0.3"
    }
  }
  backend "s3" {}
}

provider "ec" {}

locals {
  monitoring_sso_bundle_path = "./monitoring-sso-bundle.zip"
}

resource "ec_deployment" "monitoring" {
  deployment_template_id = "aws-observability"
  name                   = "Monitoring"
  region                 = "eu-west-1"
  tags                   = {}
  version                = "7.12.0"

  apm {
    elasticsearch_cluster_ref_id = "main-elasticsearch"
    ref_id                       = "main-apm"

    topology {
      instance_configuration_id = "aws.apm.r5d"
      size                      = "0.5g"
      size_resource             = "memory"
      zone_count                = 1
    }
  }

  elasticsearch {
    autoscale = "true"
    ref_id    = "main-elasticsearch"

    topology {
      id            = "hot_content"
      size          = "29g"
      size_resource = "memory"
      zone_count    = 2

      autoscaling {
        max_size          = "116g"
        max_size_resource = "memory"
      }
   }
    topology {
      id            = "ml"
      size          = "4g"
      size_resource = "memory"
      zone_count    = 1

      autoscaling {
        max_size          = "60g"
        max_size_resource = "memory"
        min_size          = "0g"
        min_size_resource = "memory"
      }
    }
    topology {
      id            = "warm"
      size          = "2g"
      size_resource = "memory"
      zone_count    = 2

      autoscaling {
        max_size          = "116g"
        max_size_resource = "memory"
      }
    }

    trust_account {
      account_id      = "[redacted]"
      trust_all       = true
      trust_allowlist = []
    }

    extension {
      name    = ec_deployment_extension.monitoring-jumpcloud.name
      type    = "bundle"
      version = "7.*"
      url     = ec_deployment_extension.monitoring-jumpcloud.url
    }
  }
  kibana {
    elasticsearch_cluster_ref_id = "main-elasticsearch"
    ref_id                       = "main-kibana"

    config {
      user_settings_yaml = <<-EOT
 [redacted SSO/SAML config]
            EOT
    }

    topology {
      instance_configuration_id = "aws.kibana.r5d"
      size                      = "1g"
      size_resource             = "memory"
      zone_count                = 1
    }
  }

  observability {
    deployment_id = "[redacted]"
    logs          = true
    metrics       = true
    ref_id        = "main-elasticsearch"
  }

  timeouts {}
}

resource "ec_deployment_extension" "monitoring-jumpcloud" {
  extension_type = "bundle"
  name           = "monitoring-jumpcloud"
  version        = "7.*"
  file_path      = local.monitoring_sso_bundle_path
  file_hash      = filebase64sha256(local.monitoring_sso_bundle_path)

  timeouts {}
}
```

## Steps to Reproduce

1. Import an existing cluster using `terraform import ec_deployment_extension.monitoring-jumpcloud [cluster-id]` and a skeleton resource in main.tf
2. Get the new resource details from the state file with `terraform state show ec_deployment_extension.monitoring-jumpcloud`
3. Fill in the skeleton resource with the info from `terraform state show`
4. Run `terraform plan`, get normal result
5. Run `terraform apply`, get failure

## Context
We are using some custom tooling around our terraform deploys, but functionally this is running `terraform apply --auto-approve -input=false tf_create.plan` where `tf_create.plan` is the output of a successful `terraform plan` command.

I'm trying to bring an existing Elastic Cloud cluster under Terraform management, and have imported with `terraform import` and created a resource to match in my terraform definition. 

## Your Environment

* Version used: 0.3.0
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud SaaS, this cluster is v7.14.2
* Environment name and version (e.g. Go 1.9): Terraform v1.0.10
* Server type and version: Docker 
* Operating System and version: Amazon Linux 2
* Link to your project: Private repo

**Comment by kylemclaren** [comment]
Experiencing this same behaviour:

```
terraform {
  required_version = ">= 1.0.10"

  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "0.3.0"
    }
  }
}
```

**Comment by selverob** [comment]
We are facing the same problem on Terraform 0.14.11, whether we run it from a Docker container or from my machine. The issue seems to be triggered any time we want to change anything on an EC deployment which has multiple Elasticsearch topology blocks and a `user_settings_yaml` set via Terraform (even when we're not changing the user settings). The output from `terraform state show` for the deployment looks like this (`__` represents redacted private data):
```hcl
resource "ec_deployment" "deployment" {
    alias                  = "__"
    deployment_template_id = "gcp-storage-optimized"
    elasticsearch_password = (sensitive value)
    elasticsearch_username = "elastic"
    id                     = "__"
    name                   = "__"
    region                 = "gcp-europe-west1"
    tags                   = {
        "env"         = "production"
    }
    traffic_filter         = [
        "__",
        "__",
    ]
    version                = "7.16.3"

    elasticsearch {
        autoscale      = "false"
        cloud_id       = "__"
        http_endpoint  = "__"
        https_endpoint = "__"
        ref_id         = "main-elasticsearch"
        region         = "gcp-europe-west1"
        resource_id    = "__"

        config {
            plugins            = [
                "repository-gcs",
            ]
            user_settings_yaml = <<-EOT
                xpack:
                  security:
                    authc:
                      realms:
                        oidc:
                          oidc1:
                            order: 2
                            rp.client_id: "__"
                            rp.response_type: "code"
                            rp.requested_scopes: ["openid", "email"]
                            rp.redirect_uri: "__/api/security/oidc/callback"
                            op.issuer: "https://accounts.google.com"
                            op.authorization_endpoint: "https://accounts.google.com/o/oauth2/v2/auth"
                            op.token_endpoint: "https://oauth2.googleapis.com/token"
                            op.userinfo_endpoint: "https://openidconnect.googleapis.com/v1/userinfo"
                            op.jwkset_path: "https://www.googleapis.com/oauth2/v3/certs"
                            claims.principal: email
                            claim_patterns.principal: "__"
            EOT
        }

        topology {
            config                    = [
                {
                    plugins                     = [
                        "repository-gcs",
                    ]
                    user_settings_json          = ""
                    user_settings_override_json = ""
                    user_settings_override_yaml = ""
                    user_settings_yaml          = ""
                },
            ]
            id                        = "coordinating"
            instance_configuration_id = "gcp.es.coordinating.n2.68x16x45"
            node_roles                = [
                "ingest",
                "remote_cluster_client",
            ]
            size                      = "4g"
            size_resource             = "memory"
            zone_count                = 3
        }
        topology {
            config                    = [
                {
                    plugins                     = [
                        "repository-gcs",
                    ]
                    user_settings_json          = ""
                    user_settings_override_json = ""
                    user_settings_override_yaml = ""
                    user_settings_yaml          = ""
                },
            ]
            id                        = "hot_content"
            instance_configuration_id = "gcp.es.datahot.n2.68x10x45"
            node_roles                = [
                "data_content",
                "data_hot",
                "remote_cluster_client",
                "transform",
            ]
            size                      = "32g"
            size_resource             = "memory"
            zone_count                = 3

            autoscaling {
                max_size          = "128g"
                max_size_resource = "memory"
            }
        }
        topology {
            config                    = [
                {
                    plugins                     = [
                        "repository-gcs",
                    ]
                    user_settings_json          = ""
                    user_settings_override_json = ""
                    user_settings_override_yaml = ""
                    user_settings_yaml          = ""
                },
            ]
            id                        = "master"
            instance_configuration_id = "gcp.es.master.n2.68x32x45"
            node_roles                = [
                "master",
                "remote_cluster_client",
            ]
            size                      = "1g"
            size_resource             = "memory"
            zone_count                = 3
        }

        trust_account {
            account_id      = "__"
            trust_all       = true
            trust_allowlist = []
        }
    }

    kibana {
        elasticsearch_cluster_ref_id = "main-elasticsearch"
        http_endpoint                = "__"
        https_endpoint               = "__"
        ref_id                       = "main-kibana"
        region                       = "gcp-europe-west1"
        resource_id                  = "__"

        config {
            user_settings_yaml = <<-EOT
                xpack.security.authc.providers:
                  oidc.oidc1:
                    order: 0
                    realm: oidc1
                    description: "Log in with Google"
                  basic.basic1:
                    order: 1
            EOT
        }

        topology {
            instance_configuration_id = "gcp.kibana.n2.68x32x45"
            size                      = "1g"
            size_resource             = "memory"
            zone_count                = 2
        }
    }

    observability {
        deployment_id = "__"
        logs          = false
        metrics       = true
        ref_id        = "main-elasticsearch"
    }
}
```

**Comment by luigibk** [comment]
I have the same issue when importing into Terraform (0.14.x) a deployment created using the rest api, with a user_settings_yaml inside a master topology configuration block in the elasticsearch block. 

Every change to that configuration will trigger a SIGSEGV as a nil pointer is dereferenced.

[PR 428](https://github.com/elastic/terraform-provider-ec/pull/428) fixes my issue.

**Comment by selverob** [comment]
@artemnikitin are you guys planning to publish a 0.3.1 or 0.4.0 release from #428?

**Comment by scathatheworm** [comment]
Could there possibly be a patch release including this?
