### ISSUE TITLE
Plugin did not respond when user_settings_yaml were provided

### ISSUE THREAD

**Issue by andrewnazarov** [elastic/terraform-provider-ec#418]
## Readiness Checklist

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
Successful `terraform apply`

## Current Behavior
I'm getting the following error when trying to set elastcsearch.config and kibana.config:
```
ec_deployment.dev: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with ec_deployment.dev,
│   on main.tf line 38, in resource "ec_deployment" "dev":
│   38: resource "ec_deployment" "dev" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-ec_v0.3.0 plugin:
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 51 [running]:
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandKibanaConfig({0x1136480, 0xc0006d3a70}, 0xc0000f0620)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/kibana_expanders.go:131 +0x397
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandKibanaResource({0x11f5d60, 0xc0007a57a0}, 0xc000698f40)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/kibana_expanders.go:71 +0x25c
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandKibanaResources({0xc000799c10, 0x1, 0x13}, 0xc000698f40)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/kibana_expanders.go:43 +0xff
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.createResourceToModel(0x40, 0xc0006d26f0)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/expanders.go:77 +0x725
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.createResource({0x163d278, 0xc0001253e0}, 0xc00061f778, {0x11162c0, 0xc0006d26f0})
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/create.go:36 +0xe7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000021880, {0x163d208, 0xc000068700}, 0x2, {0x11162c0, 0xc0006d26f0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:330 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000021880, {0x163d208, 0xc000068700}, 0xc00056b860, 0xc0002cec80, {0x11162c0, 0xc0006d26f0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:456 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0006d2138, {0x163d208, 0xc000068700}, 0xc00069a550)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00068d3e0, {0x163d2b0, 0xc0003f0180}, 0xc000216c08)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x139bc00, 0xc00068d3e0}, {0x163d2b0, 0xc0003f0180}, 0xc000124360, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004f5340, {0x164f718, 0xc0006a6480}, 0xc00054e000, 0xc0000f2330, 0x2041e40, 0x0)
	google.golang.org/grpc@v1.38.0/server.go:1286 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0004f5340, {0x164f718, 0xc0006a6480}, 0xc00054e000, 0x0)
	google.golang.org/grpc@v1.38.0/server.go:1609 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.38.0/server.go:934 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.38.0/server.go:932 +0x294
Error: The terraform-provider-ec_v0.3.0 plugin crashed!
```

## Terraform definition
> terraform --version
Terraform v1.0.6
on linux_amd64

## Steps to Reproduce
This is my simple configuration:
```
resource "ec_deployment" "dev" {
  name                   = "dev"
  region                 = "gcp-${local.region}"
  version                = data.ec_stack.latest.version

  deployment_template_id = "gcp-io-optimized-v2"

  elasticsearch {
    config {
      user_settings_yaml = file("elastic/elasticsearch.yaml")
    }
  }

  kibana {
    config {
      user_settings_yaml = file("elastic/kibana.yaml")
    }
  }

  apm {}

  enterprise_search {}
}
```
The content of kibana.yaml and elasticsearch.yaml are taken from the corresponding ES docs as it is. Since self-references are not allowed within the resource we were thinking about modifying some parameters via API calls afterwards. But so far we would like to test the ability to set SAML properties.

kibana.yaml:
```
xpack.security.authc.providers:
  saml.saml1:
    order: 0
    realm: saml1
```

elasticsearch.yaml:
```
xpack.security.authc.realms.saml.saml1:
  order: 2
  idp.metadata.path: saml/idp-metadata.xml
  idp.entity_id: "https://sso.example.com/"
  sp.entity_id:  "https://kibana.example.com/"
  sp.acs: "https://kibana.example.com/api/security/saml/callback"
  sp.logout: "https://kibana.example.com/logout"
```

**Comment by andrewnazarov** [comment]
I tried to reproduce it and couldn't. Then I found a problem. Initially, it happened that our kibana.yaml file was empty. That's why the error appeared.
