### ISSUE TITLE
ec provider plugin crashes when attempting to plan/apply an `ec_deployment_traffic_filter` resource using a count conditional

### ISSUE THREAD

**Issue by hariscodes** [elastic/terraform-provider-ec#561]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

I should be able to run a `terraform plan` or `terraform apply` when applying a terraform module that uses
a `count` conditional to optionally disable an `ec_deployment_traffic_filter` resource. 

```
resource ec_deployment_traffic_filter deployment {
  count = var.privatelink_endpoint_id == "" ? 0 : 1
  ...
}
```

Here, I'm specifying that the `ec_deployment_traffic_filter.deployment` resource should not be created if `var.privatelink_endpoint_id == ""`. This is a very common pattern in Terraform module development.

## Current Behavior

If the `count` conditional statement evaluates to 1 (i.e., it is set to create the resource) it will be able to run a `terraform plan`.

If it evaluates to 0 (i.e., I'm disabling the optional resource), it will cause the provider plugin to crash with the following error: 

```
module.ec_stack.data.ec_stack.stack: Reading...
╷
│ Error: Plugin did not respond
│
│   with module.ec_stack.data.ec_stack.stack,
│   on .terraform/modules/ec_stack/main.tf line 24, in data "ec_stack" "stack":
│   24: data ec_stack stack {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.
╵
╷
│ Error: Request cancelled
│
│   with module.ec_stack.ec_deployment_traffic_filter.deployment[0],
│   on .terraform/modules/ec_stack/main.tf line 72, in resource "ec_deployment_traffic_filter" "deployment":
│   72: resource ec_deployment_traffic_filter deployment {
│
│ The plugin.(*GRPCProvider).PlanResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-ec_v0.5.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 65 [running]:
github.com/elastic/terraform-provider-ec/ec/ecresource/trafficfilterresource.trafficFilterRuleHash({0x0?, 0x0?})
        github.com/elastic/terraform-provider-ec/ec/ecresource/trafficfilterresource/schema.go:101 +0x2a5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0x1050029?, {0x0?, 0x0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/set.go:218 +0x2c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc000484a00, {0x0?, 0x0}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/set.go:198 +0x96
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readSet(0xc0006178f0, {0xc0002577d0, 0x1, 0x1}, 0x0?)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/field_reader_config.go:284 +0x4aa
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readField(0xc0006178f0, {0xc0002577d0?, 0x1, 0x1}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/field_reader_config.go:107 +0x55b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).ReadField(0x1be7ac0?, {0xc0002577d0?, 0x1d85a87?, 0x6?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/field_reader_config.go:29 +0xbc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc0002577b0?, {0xc0002577d0, 0x1, 0x1}, {0x1d85a87, 0x6})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/field_reader_multi.go:31 +0xa8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0xc000470d00, {0xc0002577d0, 0x1, 0x1}, 0x0?)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource_data.go:548 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).getChange(0xc00089ef00?, {0x1d840d7?, 0x4?}, 0xb0?, 0x76?)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource_data.go:524 +0x1b8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).diffChange(0xc0005d8a20?, {0x1d840d7?, 0xc000470d00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource_data.go:501 +0x76
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffSet(0xc0006177d0?, {0x1f2cac0, 0xc000616b70}, {0x1d840d7, 0x4}, 0xc000412140, 0xc0005d8da0, {0x1f2fa00?, 0xc000470d00?}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/schema.go:1412 +0x90
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x6?, {0x1f2cac0, 0xc000616b70}, {0x1d840d7, 0x4}, 0xc000412140, 0xc000470c80, {0x1f2fa00?, 0xc000470d00}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/schema.go:1134 +0x265
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc00040b2f0, {0x1f2cac0, 0xc000616b70}, 0xc0005c6750, 0xc0006176e0, 0x0, {0x1b351e0, 0xc00013c4e0}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/schema.go:679 +0x353
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x1f2d1f8?, {0x1f2cac0?, 0xc000616b70?}, 0xc0005c6750, 0x1be83c0?, {0x1b351e0?, 0xc00013c4e0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:890 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0003199e0, {0x1f2cac0?, 0xc000616a50?}, 0xc0001c6910)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:741 +0x9c9
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc0004b4640, {0x1f2cac0?, 0xc000616210?}, 0xc0004c2150)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:783 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x1d45ca0?, 0xc0004b4640}, {0x1f2cac0, 0xc000616210}, 0xc0004c20e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00035c000, {0x1f30b00, 0xc000582d00}, 0xc0005a6000, 0xc00040b560, 0x27230e8, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc00035c000, {0x1f30b00, 0xc000582d00}, 0xc0005a6000, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-ec_v0.5.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

## Terraform definition

```(hcl)
terraform {
  required_version = "~> 1.0"

  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "~> 0.0"
    }
  }
}

resource ec_deployment_traffic_filter deployment {
  count = var.privatelink_endpoint_id == "" ? 0 : 1

  name   = "${var.name}-privatelink"
  region = var.region
  type   = "vpce"

  rule {
    source = var.privatelink_endpoint_id
  }
}
```

## Steps to Reproduce

Run `terraform plan` on a `ec_deployment_traffic_filter` resource with a count conditional

## Context

I'm unable to add an optional traffic filter to my Elastic Stack module.

## Your Environment

* Version used: `0.5.0`, but also tried `0.4.1` and `0.4.0`
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: `8.4.1`
* Environment name and version (e.g. Go 1.9): Terraform `1.3.4`
* Server type and version: N/A
* Operating System and version: MacOS Monterey 12.6
* Link to your project: N/A

**Comment by tobio** [comment]
Cannot reproduce this with 0.8.0
