### ISSUE TITLE
elastic/ec terraform provider plugin throws null pointer exception while reading data source

### ISSUE THREAD

**Issue by roy-tancredi** [elastic/terraform-provider-ec#673]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Read data source
## Current Behavior

```
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadDataSource call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-ec_v0.7.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10538b1a8]

goroutine 55 [running]:
github.com/elastic/terraform-provider-ec/ec/ecdatasource/deploymentdatasource.modelToState({0x105a80460?, 0x1400040d560?}, 0x20?, 0x140005fc200)
	github.com/elastic/terraform-provider-ec/ec/ecdatasource/deploymentdatasource/datasource.go:112 +0x158
github.com/elastic/terraform-provider-ec/ec/ecdatasource/deploymentdatasource.DataSource.Read({0x0?}, {0x105a80460, 0x1400040d560}, {{{{0x105a84e00, 0x140006cbe00}, {0x1058b9b80, 0x140006cb2c0}}, {0x1400064f830, 0x0, 0x0, ...}}, ...}, ...)
	github.com/elastic/terraform-provider-ec/ec/ecdatasource/deploymentdatasource/datasource.go:90 +0x310
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0x140001e74a0, {0x105a80460, 0x1400040d560}, 0x1400040d650, 0x1400076d5e8)
	github.com/hashicorp/terraform-plugin-framework@v0.14.0/internal/fwserver/server_readdatasource.go:75 +0x418
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0x140001e74a0, {0x105a80460?, 0x1400040d410?}, 0x1400050a640)
	github.com/hashicorp/terraform-plugin-framework@v0.14.0/internal/proto6server/server_readdatasource.go:52 +0x1b0
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0x14000124820, {0x105a80460?, 0x1400040c2d0?}, 0x140006a5090)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:656 +0x368
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x105a30ee0?, 0x14000124820}, {0x105a80460, 0x1400040c2d0}, 0x1400023e460, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000161e0, {0x105a85140, 0x1400019a680}, 0x140006fc240, 0x140003dbbc0, 0x1062ac730, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x140000161e0, {0x105a85140, 0x1400019a680}, 0x140006fc240, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x290

Error: The terraform-provider-ec_v0.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
## Terraform definition

Not applicable. Not sure which context is causing reading deployment data fail.
## Steps to Reproduce

Not applicable. Not sure which context is causing reading deployment data fail.

## Your Environment

* Version used: 0.7.0
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud SaaS
* Environment name and version (e.g. Go 1.9): Terraform 1.5.2
* Server type and version: -
* Operating System and version: MacOS
* Link to your project:

**Comment by tobio** [comment]
@roy-tancredi are you able to share a deployment ID that's causing this crash?

**Comment by roy-tancredi** [comment]
@tobio I'm not sure if it deployment still exists, because it was early testing stage. But I was able to reproduce this error with provider v0.8.0. The id of deployment was `cd30d9bebb8150757b60c6bfc7d68359`.
```
data.ec_deployment.elastic: Reading...
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ReadDataSource call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-ec_v0.8.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102c29f4c]

goroutine 41 [running]:
github.com/elastic/terraform-provider-ec/ec/ecdatasource/deploymentdatasource.modelToState({0x1033686c0?, 0x140006ba330?}, 0x20?, 0x1400060e800)
	github.com/elastic/terraform-provider-ec/ec/ecdatasource/deploymentdatasource/datasource.go:112 +0x15c
github.com/elastic/terraform-provider-ec/ec/ecdatasource/deploymentdatasource.DataSource.Read({0x0?}, {0x1033686c0, 0x140006ba330}, {{{{0x10336d6c0, 0x14000703ad0}, {0x103193c80, 0x14000703050}}, {0x10336f598, 0x14000616c40}}, {{{0x0, ...}, ...}, ...}}, ...)
	github.com/elastic/terraform-provider-ec/ec/ecdatasource/deploymentdatasource/datasource.go:90 +0x350
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0x14000321760, {0x1033686c0, 0x140006ba330}, 0x140006ba3c0, 0x1400048f5e8)
	github.com/hashicorp/terraform-plugin-framework@v1.3.4/internal/fwserver/server_readdatasource.go:79 +0x394
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0x14000321760, {0x1033686c0?, 0x140006ba1e0?}, 0x140005b2ea0)
	github.com/hashicorp/terraform-plugin-framework@v1.3.4/internal/proto6server/server_readdatasource.go:55 +0x1b0
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0x140005495e0, {0x1033686c0?, 0x14000677860?}, 0x140005aeff0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:659 +0x368
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x10330f680?, 0x140005495e0}, {0x1033686c0, 0x14000677860}, 0x14000222a10, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:458 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140006581e0, {0x10336da00, 0x14000582d00}, 0x1400068d8c0, 0x14000383590, 0x103bd55f0, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1337 +0xc64
google.golang.org/grpc.(*Server).handleStream(0x140006581e0, {0x10336da00, 0x14000582d00}, 0x1400068d8c0, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1714 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.1/server.go:959 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.1/server.go:957 +0x16c

Error: The terraform-provider-ec_v0.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by tobio** [comment]
> In case of replacement or destruction the ec_deployment go first, then there is no deployment to refer, but still the data source has id passed by azurerm_elastic_cloud_elasticsearchand hence the crash.

Ah, this makes sense. It wasn't clear how you'd get into this situation with anything but a deleted deployment. Regardless, the provider shouldn't crash here, thanks for the report, and help in tracking down the cause.

**Comment by roy-tancredi** [comment]
@tobio it is quite simple :D – the import process of deployment needs some pumblings to be in place (`ref_id`s, etc.). To do not hardcoding them, I use data source for that. I described the process in other issue – https://github.com/elastic/terraform-provider-ec/issues/655
