### ISSUE TITLE
EC provider v0.9.0 segfaults while modifying ec_deployment resource

### ISSUE THREAD

**Issue by peikk0** [elastic/terraform-provider-ec#715]
After updating the provider from v0.7.0 to v0.9.0 it segfaults while updating an `ec_deployment` resource.

## Readiness Checklist

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

The provider doesn't segfault and the resource is updated.

## Current Behavior

```
Terraform will perform the following actions:
  # ec_deployment.monitoring will be updated in-place
  ~ resource "ec_deployment" "monitoring" {
      ~ elasticsearch          = {
          + trust_account  = (known after apply)
          + trust_external = (known after apply)
            # (16 unchanged attributes hidden)
        }
        id                     = "XXX"
        name                   = "monitoring-cluster"
      + traffic_filter         = []
        # (5 unchanged attributes hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

```
ec_deployment.monitoring: Modifying... [id=0ea4e34a81444a95a1adeb1f90ed9dfa]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-ec_v0.9.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xd250ff]
goroutine 30 [running]:
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2.elasticsearchSnapshotPayload({0x147acb0, 0xc0005a76e0}, {0x147d330, 0xc000698ee8}, 0xc0000692c0)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_snapshot.go:101 +0x31f
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2.(*ElasticsearchTF).payload(0xc000416000, {0x147acb0, 0xc0005a76e0}, 0xc00086d530, 0x102dba0?)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload.go:109 +0x313
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2.ElasticsearchPayload({0x147acb0, 0xc0005a76e0}, {0xc0005e5b90, 0xc0005d7650, 0x2}, 0x5?, 0xc0008690e0, {0xc00065c460, 0x1e}, {0xc000013437, ...}, ...)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload.go:75 +0x466
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/deployment/v2.DeploymentTF.UpdateRequest({{0x2, {0xc00065c680, 0x20}}, {0x2, {0x0, 0x0}}, {0x2, {0xc000013437, 0x5}}, {0x2, ...}, ...}, ...)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/deployment/v2/deployment_update_payload.go:130 +0x587
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.(*Resource).Update(0xc0001186d0, {0x147acb0, 0xc0005a76e0}, {{{{0x147fc20, 0xc0005c2930}, {0x10d7200, 0xc00063d620}}, {0x1482310, 0xc00069ef50}}, {{{0x147fc20, ...}, ...}, ...}, ...}, ...)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/update.go:50 +0x4f1
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).UpdateResource(0xc000197080, {0x147acb0, 0xc0005a76e0}, 0xc0008673e8, 0xc0008672f8)
	github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/fwserver/server_updateresource.go:122 +0x70e
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc0004bb500?, {0x147acb0, 0xc0005a76e0}, 0xc00069e6e0, 0xc000867500)
	github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/fwserver/server_applyresourcechange.go:102 +0x19e
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc000197080, {0x147acb0?, 0xc0005a7560?}, 0xc00069e640)
	github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/proto6server/server_applyresourcechange.go:55 +0x3ff
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0005220a0, {0x147acb0?, 0xc0005a6330?}, 0xc0002f2460)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:819 +0x56a
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x126df20?, 0xc0005220a0}, {0x147acb0, 0xc0005a6330}, 0xc0002f23f0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000016000, {0x14807e0, 0xc0004e6820}, 0xc000494000, 0xc000692fc0, 0x1e4f780, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1337 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc000016000, {0x14807e0, 0xc0004e6820}, 0xc000494000, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1714 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.1/server.go:959 +0x8d
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 9
	google.golang.org/grpc@v1.56.1/server.go:957 +0x165
Error: The terraform-provider-ec_v0.9.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

## Terraform definition

```terraform
resource "ec_deployment" "monitoring" {
  name                   = "monitoring-cluster"
  region                 = "gcp-us-central1"
  version                = "8.7.1"
  deployment_template_id = "gcp-storage-optimized-dense-v3"

  elasticsearch = {
    ref_id = "elasticsearch"
    config = {
      plugins = ["repository-gcs", ]

      user_settings_yaml = <<-EOT
          ...
      EOT
    }

    master = {
      autoscaling = {}
      zone_count  = 3
    }

    coordinating = {
      autoscaling = {}
      zone_count  = 2
    }

    hot = {
      autoscaling = {}
    }

    warm = {
      autoscaling = {}
    }

    cold = {
      autoscaling = {}
    }
    frozen = {
      autoscaling = {}
    }
    ml = {
      autoscaling = {}
    }
  }

  kibana = {
    ref_id                       = "kibana"
    elasticsearch_cluster_ref_id = "elasticsearch"
    config = {
      user_settings_yaml = <<-EOT
              ...
            EOT
    }
  }

  observability = {
    deployment_id = "self"
  }
}
```

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Terraform v1.5.6, EC Provider v0.6.0
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version:
* Environment name and version (e.g. Go 1.9):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by dimuon** [comment]
@peikk0 , I struggled to reproduce the issue with the provided TF config. Maybe I'm missing something. Can you specify minimal TF configuration that can be used to repro the issue? IIUC, to repro the issue we need to 
- create deployment with the provider v0.7.0
- update the provider to v0.9.0 (I suspect that it can happen with 0.8.0 as well though)
- update the deployment.
Is that correct?

**Comment by danielmitterdorfer** [comment]
@dimuon the following reproduces for me with v0.9.0:

```terraform
terraform {

  required_version = "~> 1"

  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "0.9.0"
    }
  }
}

provider "ec" {
  # Set EC_API_KEY in your env, with the same apiKey used for ecctl
}

resource "ec_deployment" "profiling" {
  name                   = "tf-deployment"
  version                = "8.11.0-SNAPSHOT"
  region                 = "gcp-us-west2"
  deployment_template_id = "gcp-io-optimized-v3"

  elasticsearch = {
    autoscale = false
    strategy  = "rolling_all"

    hot = {
      autoscaling = {}
      size       = "4g"
      zone_count = 1
    }

    snapshot_source = {
        source_elasticsearch_cluster_id = "INSERT_A_CLUSTER_ID_HERE"
    }
  }

  kibana = {
    size = "1g"
  }
}
```

`terraform apply` and confirming the output with `yes`, leads to:

```
ec_deployment.profiling: Creating...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-ec_v0.9.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd238fa]

goroutine 55 [running]:
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2.elasticsearchStrategyPayload({0xb0?, {0xc0005a5960?, 0x0?}}, 0xc0005a8380)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload.go:273 +0x1da
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2.(*ElasticsearchTF).payload(0xc000474000, {0x147acb0, 0xc000630b40}, 0xc00063a8d0, 0x102dba0?)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload.go:129 +0x725
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2.ElasticsearchPayload({0x147acb0, 0xc000630b40}, {0xc00063ad50, 0xc00071c240, 0x2}, 0x0?, 0xc00085e940, {0xc000047800, 0x13}, {0xc0005a5a80, ...}, ...)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/elasticsearch/v2/elasticsearch_payload.go:75 +0x466
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/deployment/v2.DeploymentTF.CreateRequest({{0x1, {0x0, 0x0}}, {0x1, {0x0, 0x0}}, {0x2, {0xc0005a5a80, 0xf}}, {0x2, ...}, ...}, ...)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/deployment/v2/deployment_create_payload.go:102 +0x4b4
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.(*Resource).Create(0xc000130078, {0x147acb0, 0xc000630b40}, {{{{0x147fc20, 0xc000603890}, {0x10d7200, 0xc0006c49c0}}, {0x1482310, 0xc0005c6280}}, {{{0x147fc20, ...}, ...}, ...}, ...}, ...)
	github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/create.go:50 +0x494
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0001fd1e0, {0x147acb0, 0xc000630b40}, 0xc00085f3a8, 0xc00085f348)
	github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/fwserver/server_createresource.go:101 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc00078b500?, {0x147acb0, 0xc000630b40}, 0xc0006138b0, 0xc00085f500)
	github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/fwserver/server_applyresourcechange.go:57 +0x4a5
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc0001fd1e0, {0x147acb0?, 0xc000630a20?}, 0xc000613810)
	github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/proto6server/server_applyresourcechange.go:55 +0x3ff
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0003f9b80, {0x147acb0?, 0xc000630030?}, 0xc000462230)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:819 +0x56a
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x126df20?, 0xc0003f9b80}, {0x147acb0, 0xc000630030}, 0xc0004621c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b65a0, {0x14807e0, 0xc0005571e0}, 0xc0000eaa20, 0xc000396ff0, 0x1e4f780, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1337 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0000b65a0, {0x14807e0, 0xc0005571e0}, 0xc0000eaa20, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1714 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.1/server.go:959 +0x8d
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 40
	google.golang.org/grpc@v1.56.1/server.go:957 +0x165

Error: The terraform-provider-ec_v0.9.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

If I remove `strategy`, then this works just fine.
